import { Channel, WatchedVideo } from './types';

export const MOCK_CHANNELS: Channel[] = [
  {
    id: 'c1',
    name: 'TechFlow',
    category: 'Technology',
    subscriberCount: 2500000,
    totalVideos: 450,
    avatarUrl: 'https://picsum.photos/100/100?random=1',
    description: 'Deep dives into the latest consumer electronics and coding tutorials.',
    userTags: ['coding', 'gadgets'],
    suggestedTags: [],
    isFavorite: true,
    favoriteRank: 1,
  },
  {
    id: 'c2',
    name: 'GamerNexus',
    category: 'Gaming',
    subscriberCount: 1800000,
    totalVideos: 1200,
    avatarUrl: 'https://picsum.photos/100/100?random=2',
    description: 'Hardware reviews and high-performance PC building.',
    userTags: ['hardware'],
    suggestedTags: [],
    isFavorite: false,
    favoriteRank: 0,
  },
  {
    id: 'c3',
    name: 'Culinary Quest',
    category: 'Food',
    subscriberCount: 850000,
    totalVideos: 300,
    avatarUrl: 'https://picsum.photos/100/100?random=3',
    description: 'Exploring street food cultures around the world.',
    userTags: ['recipes', 'travel'],
    suggestedTags: [],
    isFavorite: false,
    favoriteRank: 0,
  },
  {
    id: 'c4',
    name: 'History Buffer',
    category: 'Education',
    subscriberCount: 5000000,
    totalVideos: 80,
    avatarUrl: 'https://picsum.photos/100/100?random=4',
    description: 'Mini-documentaries about obscure historical events.',
    userTags: [],
    suggestedTags: [],
    isFavorite: true,
    favoriteRank: 2,
  },
  {
    id: 'c5',
    name: 'FitLife Pro',
    category: 'Health',
    subscriberCount: 120000,
    totalVideos: 600,
    avatarUrl: 'https://picsum.photos/100/100?random=5',
    description: 'Daily workout routines and nutrition advice.',
    userTags: ['workout'],
    suggestedTags: [],
    isFavorite: false,
    favoriteRank: 0,
  },
  {
    id: 'c6',
    name: 'Code Wizardry',
    category: 'Technology',
    subscriberCount: 320000,
    totalVideos: 150,
    avatarUrl: 'https://picsum.photos/100/100?random=6',
    description: 'Advanced algorithms and system design interviews.',
    userTags: ['algorithms', 'career'],
    suggestedTags: [],
    isFavorite: false,
    favoriteRank: 0,
  }
];

export const MOCK_HISTORY: WatchedVideo[] = [
  {
    id: 'v1',
    channelId: 'c1',
    title: 'The Future of AI in 2025',
    watchedDate: '2023-10-25',
    rating: 5,
    commentary: 'Great insights on LLMs.',
  },
  {
    id: 'v2',
    channelId: 'c2',
    title: 'RTX 5090 Review',
    watchedDate: '2023-10-25',
    rating: 4,
    commentary: 'A bit too technical but good benchmarks.',
  },
  {
    id: 'v3',
    channelId: 'c3',
    title: 'Street Food in Tokyo',
    watchedDate: '2023-10-26',
    rating: 5,
    commentary: 'Made me hungry immediately.',
  },
  {
    id: 'v4',
    channelId: 'c1',
    title: 'React 19 Features',
    watchedDate: '2023-10-27',
    rating: 4,
    commentary: '',
  },
  {
    id: 'v5',
    channelId: 'c4',
    title: 'The Fall of Rome - Part 1',
    watchedDate: '2023-10-27',
    rating: 3,
    commentary: 'Pacing was slow.',
  }
];